// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pceqfaaquckkaittrwkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZXFmYWFxdWNra2FpdHRyd2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NTc5NjksImV4cCI6MjA2MTEzMzk2OX0.t5IsaALHEENkYsffURiASA4qCR330Jwvj62uf-ryMto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);